choco install -y foobar2000
choco install -y vlc
choco install -y spotify
choco install -y audacity
choco install -y audacity-lame
choco install -y audacity-ffmpeg
choco install -y ffmpeg
choco install -y youtube-dl
choco install -y asio4all