choco install -y 7zip.install
choco install -y sysinternals
choco install -y nordvpn
choco install -y winscp.install
choco install -y qbittorrent
choco install -y webtorrent-desktop
choco install -y paint.net
choco install -y bitwarden
choco install -y bitwarden-cli
choco install -y keepassxc
choco install -y authy-desktop
choco install -y bleachbit.install
choco install -y treesizefree
choco install -y rambox
choco install -y slack
choco install -y sumatrapdf.install
choco install -y google-backup-and-sync
choco install -y stack
choco install -y dropbox
choco install -y cmder
choco install -y awscli
choco install -y terraform
choco install -y mremoteng
choco install -y notion
choco install -y todoist
choco install -y sharex
